##################
# For Github User
# github_username: "slack_member_id"

tancoro: "knishino"
whq-hqw: "hwang"
tancoro-sub: "knishino"
mekyas: "ymektoubi"
cweihong118: "wchin"

##################
# For Github Team
# github_teamname: "slack_member_id"

pop1: "pd_01_team"
